# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

# server {
# 	listen 80 default_server;
# 	listen [::]:80 default_server;

# 	index index.html

# 	# Everything is a 404
# 	location / {
# 		return 404;
# 	}

# 	# You may need this to prevent return 404 recursion.
# 	location = /404.html {
# 		internal;
# 	}
# }

server {
    listen 80;
    listen [::]:80;
    server_name gsoteldo.42.fr localhost;
    
    # Devolver error 426 (Upgrade Required)
    return 426 "HTTPS Required\n";
}


server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name gsoteldo.42.fr;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

	location ~ \.php$ {
		fastcgi_pass wp-php:9000;
		fastcgi_index index.php;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
		
	}
}
